all: addition_subtraction.cpp multiplication_division.cpp fibonacci-sequence.cpp
	g++ addition_subtraction.cpp -o addition_subtraction
	g++ multiplication_division.cpp -o multiplication_division
	g++ fibonacci-sequence.cpp -o fibonacci-sequence

clean:
	@rm -rf addition_subtraction
	@rm -rf multiplication_division
	@rm -rf fibonacci-sequence
