all: main.cpp no_main.cpp int.cpp void.cpp
	g++ main.cpp -o main
	g++ no_main.cpp -o no_main
	g++ int.cpp -o int
	g++ void.cpp -o void

clean:
	@rm -rf main
	@rm -rf no_main
	@rm -rf int
	@rm -rf void
